In [18]:
import sqlite3
import numpy as np
import pandas as pd
import pymysql
import pandas as pd
import numpy as np
import seaborn as sns
import mysql.connector
from glob import glob
from collections import Counter
from collections import defaultdict
from datetime import datetime

pd.set_option('display.max_columns', None)

res_df = pd.read_csv('res_df.csv')

care_df = pd.read_csv('care_df.csv')

In [19]:
import mysql.connector

dbcon = { 'host': 'db-hf42t.pub-cdb.ntruss.com',
          'user': 'scott',
          'password' : 'love1103!@',
          'database': 'campusDB'}

conn = mysql.connector.connect(**dbcon)
cursor = conn.cursor()
sql = "show tables"
cursor.execute(sql)
res = cursor.fetchall()
# con.close()

In [20]:
suitecare_data = pymysql.connect(
user = 'scott',
password = 'love1103!@',
host = 'db-hf42t.pub-cdb.ntruss.com',
database = 'campusDB',
charset = 'utf8')

In [21]:
cursor = suitecare_data.cursor()
sql = "select * from reservation_info;"
cursor.execute(sql)
result = cursor.fetchall()
result

(('RES00003',
  datetime.date(2023, 8, 24),
  datetime.date(2023, 8, 31),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=64800),
  'SC00002',
  '서울특별시',
  '경기도',
  '인천광역시',
  '40~44',
  '지정하지 않음',
  '지정하지 않음',
  '상관없음',
  '요양보호사',
  '재활운동보조',
  '외출동행',
  '지정하지 않음',
  '11000',
  '지정하지 않음',
  '지정하지 않음',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '선호성별',
  '시급'),
 ('RES00005',
  datetime.date(2023, 8, 24),
  datetime.date(2023, 8, 28),
  datetime.timedelta(seconds=39600),
  datetime.timedelta(seconds=64800),
  'SC00005',
  '서울특별시',
  '경기도',
  '인천광역시',
  '50~54',
  '45~49',
  '40~44',
  '상관없음',
  '지정하지 않음',
  '요리',
  '운전',
  '지정하지 않음',
  '10000',
  '11000',
  '지정하지 않음',
  '시급',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '선호성별'),
 ('RES00006',
  datetime.date(2023, 8, 22),
  datetime.date(2023, 8, 23),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=64800),
  'SC00004',
  '경기도',
  '서울특별시',
  '인천광역시',
  '30~34',
  '34~39',
  '40~44',
  'W',
  '요양보호사',
  '운전',
  '요리',
  '청소',
  '10000',
  '12000',
  '11000',
  '선호성별',
  '시급',
  '선호서비스',
  '선호지역',
  '선호나이대'),
 ('RES00007',
  datetime.date(2023, 8, 25),
  datetime.date(2023, 8, 26),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=46800),
  'SC00004',
  '제주특별자치도',
  '부산광역시',
  '서울특별시',
  '45~49',
  '55~59',
  '65~69',
  '상관없음',
  '지정하지 않음',
  '산책',
  '요리',
  '청소',
  '10000',
  '11000',
  '지정하지 않음',
  '선호나이대',
  '선호성별',
  '시급',
  '선호서비스',
  '선호지역'),
 ('RES00008',
  datetime.date(2023, 8, 22),
  datetime.date(2023, 8, 26),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=46800),
  'SC00010',
  '인천광역시',
  '경기도',
  '제주특별자치도',
  '34~39',
  '30~34',
  '55~59',
  'M',
  '물리치료사',
  '재활운동보조',
  '외출동행',
  '청소',
  '11000',
  '13000',
  '12000',
  '선호지역',
  '선호나이대',
  '선호성별',
  '시급',
  '선호서비스'),
 ('RES00009',
  datetime.date(2023, 8, 24),
  datetime.date(2023, 8, 30),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=46800),
  'SC00010',
  '경기도',
  '서울특별시',
  '인천광역시',
  '45~49',
  '60~64',
  '65~69',
  '상관없음',
  '요양보호사',
  '산책',
  '돌봄',
  '지정하지 않음',
  '10000',
  '12000',
  '11000',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '선호성별',
  '시급'),
 ('RES00010',
  datetime.date(2023, 8, 24),
  datetime.date(2023, 8, 28),
  datetime.timedelta(seconds=57600),
  datetime.timedelta(seconds=64800),
  'SC00009',
  '제주특별자치도',
  '서울특별시',
  '부산광역시',
  '45~49',
  '40~44',
  '50~54',
  'W',
  '지정하지 않음',
  '지정하지 않음',
  '지정하지 않음',
  '지정하지 않음',
  '11000',
  '12000',
  '10000',
  '시급',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '선호성별'),
 ('RES00011',
  datetime.date(2023, 9, 4),
  datetime.date(2023, 9, 8),
  datetime.timedelta(seconds=39600),
  datetime.timedelta(seconds=57600),
  'SC00011',
  '서울특별시',
  '지정하지 않음',
  '지정하지 않음',
  '40~44',
  '45~49',
  '지정하지 않음',
  'W',
  '요양보호사',
  '재활운동보조',
  '외출동행',
  '지정하지 않음',
  '10000',
  '11000',
  '12000',
  '선호성별',
  '시급',
  '선호서비스',
  '선호지역',
  '선호나이대'),
 ('RES00013',
  datetime.date(2023, 8, 28),
  datetime.date(2023, 8, 31),
  datetime.timedelta(seconds=61200),
  datetime.timedelta(seconds=64800),
  'SC00012',
  '서울특별시',
  '경기도',
  '인천광역시',
  '40~44',
  '45~49',
  '50~54',
  'W',
  '요양보호사',
  '재활운동보조',
  '외출동행',
  '운전',
  '10000',
  '11000',
  '12000',
  '선호나이대',
  '선호성별',
  '시급',
  '선호서비스',
  '선호지역'),
 ('RES00014',
  datetime.date(2023, 8, 28),
  datetime.date(2023, 9, 8),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=64800),
  'SC00014',
  '인천광역시',
  '서울특별시',
  '제주특별자치도',
  '34~39',
  '55~59',
  '40~44',
  'M',
  '물리치료사',
  '외출동행',
  '재활운동보조',
  '운전',
  '11000',
  '10000',
  '12000',
  '선호지역',
  '선호나이대',
  '선호성별',
  '시급',
  '선호서비스'),
 ('RES00016',
  datetime.date(2023, 8, 27),
  datetime.date(2023, 8, 31),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=61200),
  'SC00015',
  '서울특별시',
  '경기도',
  '지정하지 않음',
  '45~49',
  '50~54',
  '40~44',
  'M',
  '지정하지 않음',
  '요리',
  '목욕',
  '재활운동보조',
  '10000',
  '11000',
  '12000',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '선호성별',
  '시급'),
 ('RES00017',
  datetime.date(2023, 8, 27),
  datetime.date(2023, 8, 31),
  datetime.timedelta(seconds=46800),
  datetime.timedelta(seconds=61200),
  'SC00012',
  '서울특별시',
  '경기도',
  '지정하지 않음',
  '65~69',
  '45~49',
  '40~44',
  'M',
  '물리치료사',
  '빨래',
  '외출동행',
  '지정하지 않음',
  '10000',
  '13000',
  '11000',
  '시급',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '선호성별'),
 ('RES00018',
  datetime.date(2023, 8, 26),
  datetime.date(2023, 8, 30),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=57600),
  'SC00003',
  '인천광역시',
  '경기도',
  '서울특별시',
  '60~64',
  '55~59',
  '50~54',
  '상관없음',
  '지정하지 않음',
  '재활운동보조',
  '외출동행',
  '청소',
  '11000',
  '12000',
  '10000',
  '선호성별',
  '시급',
  '선호서비스',
  '선호지역',
  '선호나이대'),
 ('RES00019',
  datetime.date(2023, 8, 28),
  datetime.date(2023, 9, 1),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=46800),
  'SC00011',
  '서울특별시',
  '경기도',
  '인천광역시',
  '60~64',
  '34~39',
  '50~54',
  'M',
  '물리치료사',
  '운전',
  '재활운동보조',
  '외출동행',
  '10000',
  '11000',
  '13000',
  '선호나이대',
  '선호성별',
  '시급',
  '선호서비스',
  '선호지역'),
 ('RES00020',
  datetime.date(2023, 8, 29),
  datetime.date(2023, 9, 5),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=46800),
  'SC00017',
  '서울특별시',
  '경기도',
  '지정하지 않음',
  '40~44',
  '50~54',
  '50~54',
  'M',
  '지정하지 않음',
  '외출동행',
  '재활운동보조',
  '목욕',
  '11000',
  '15000',
  '13000',
  '선호지역',
  '선호나이대',
  '선호성별',
  '시급',
  '선호서비스'),
 ('RES00021',
  datetime.date(2023, 8, 29),
  datetime.date(2023, 9, 4),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=57600),
  'SC00009',
  '서울특별시',
  '경기도',
  '인천광역시',
  '40~44',
  '50~54',
  '45~49',
  '상관없음',
  '물리치료사',
  '목욕',
  '운전',
  '재활운동보조',
  '10000',
  '11000',
  '12000',
  '선호지역',
  '선호나이대',
  '선호서비스',
  '선호성별',
  '시급'),
 ('RES00022',
  datetime.date(2023, 8, 29),
  datetime.date(2023, 9, 14),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=50400),
  'SC00017',
  '경기도',
  '제주특별자치도',
  '인천광역시',
  '30~34',
  '34~39',
  '40~44',
  None,
  '요양보호사',
  '빨래',
  '운전',
  '재활운동보조',
  '11000',
  '10000',
  '12000',
  '선호서비스',
  '선호지역',
  '시급',
  '선호성별',
  '선호나이대'),
 ('RES00023',
  datetime.date(2023, 9, 5),
  datetime.date(2023, 9, 8),
  datetime.timedelta(seconds=39600),
  datetime.timedelta(seconds=50400),
  'SC00002',
  '서울특별시',
  '지정하지 않음',
  '지정하지 않음',
  '40~44',
  '45~49',
  '지정하지 않음',
  '상관없음',
  '지정하지 않음',
  '재활운동보조',
  '외출동행',
  '지정하지 않음',
  '10000',
  '11000',
  '12000',
  '선호서비스',
  '선호지역',
  '선호나이대',
  '시급',
  '선호성별'),
 ('RES00024',
  datetime.date(2023, 9, 19),
  datetime.date(2023, 9, 22),
  datetime.timedelta(seconds=43200),
  datetime.timedelta(seconds=64800),
  'SC00011',
  '서울특별시',
  '지정하지 않음',
  '지정하지 않음',
  '50~54',
  '40~44',
  '45~49',
  '상관없음',
  '지정하지 않음',
  '재활운동보조',
  '외출동행',
  '목욕',
  '10000',
  '지정하지 않음',
  '지정하지 않음',
  '선호지역',
  '선호서비스',
  '선호나이대',
  '시급',
  '선호성별'),
 ('RES00025',
  datetime.date(2023, 8, 29),
  datetime.date(2023, 9, 2),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=64800),
  'SC00017',
  '경기도',
  '인천광역시',
  '제주특별자치도',
  '30~34',
  '40~44',
  '60~64',
  'M',
  '요양보호사',
  '운전',
  '목욕',
  '빨래',
  '11000',
  '12000',
  '10000',
  '선호나이대',
  '선호지역',
  '시급',
  '선호성별',
  '선호서비스'),
 ('RES00026',
  datetime.date(2023, 9, 1),
  datetime.date(2023, 9, 5),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=64800),
  'SC00018',
  '경기도',
  '제주특별자치도',
  '인천광역시',
  '30~34',
  '40~44',
  '50~54',
  'W',
  '물리치료사',
  '목욕',
  '빨래',
  '운전',
  '13000',
  '10000',
  '12000',
  '선호서비스',
  '선호성별',
  '시급',
  '선호나이대',
  '선호지역'),
 ('RES00027',
  datetime.date(2023, 9, 1),
  datetime.date(2023, 9, 5),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=64800),
  'SC00019',
  '인천광역시',
  '제주특별자치도',
  '서울특별시',
  '60~64',
  '30~34',
  '40~44',
  'M',
  '지정하지 않음',
  '목욕',
  '운전',
  '재활운동보조',
  '10000',
  '11000',
  '12000',
  '시급',
  '선호성별',
  '선호서비스',
  '선호나이대',
  '선호지역'),
 ('RES00028',
  datetime.date(2023, 9, 2),
  datetime.date(2023, 9, 5),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=57600),
  'SC00003',
  '제주특별자치도',
  '인천광역시',
  '서울특별시',
  '40~44',
  '60~64',
  '45~49',
  '상관없음',
  '물리치료사',
  '운전',
  '빨래',
  '재활운동보조',
  '11000',
  '10000',
  '12000',
  '선호지역',
  '시급',
  '선호성별',
  '선호서비스',
  '선호나이대'),
 ('RES00029',
  datetime.date(2023, 9, 25),
  datetime.date(2023, 9, 29),
  datetime.timedelta(seconds=36000),
  datetime.timedelta(seconds=50400),
  'SC00002',
  '서울특별시',
  '경기도',
  '인천광역시',
  '45~49',
  '40~44',
  '30~34',
  '상관없음',
  '요양보호사',
  '재활운동보조',
  '빨래',
  '청소',
  '10000',
  '11000',
  '12000',
  '선호지역',
  '선호나이대',
  '선호서비스',
  '시급',
  '선호성별'),
 ('RES00030',
  datetime.date(2023, 9, 8),
  datetime.date(2023, 9, 11),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=64800),
  'SC00003',
  '제주특별자치도',
  '서울특별시',
  '경기도',
  '30~34',
  '60~64',
  '40~44',
  'W',
  '지정하지 않음',
  '빨래',
  '재활운동보조',
  '요리',
  '10000',
  '11000',
  '12000',
  '선호나이대',
  '선호성별',
  '선호지역',
  '선호서비스',
  '시급'),
 ('RES00031',
  datetime.date(2023, 9, 6),
  datetime.date(2023, 9, 10),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=57600),
  'SC00026',
  '경기도',
  '제주특별자치도',
  '인천광역시',
  '45~49',
  '30~34',
  '40~44',
  'W',
  '물리치료사',
  '외출동행',
  '빨래',
  '청소',
  '11000',
  '10000',
  '12000',
  '선호나이대',
  '시급',
  '선호성별',
  '선호지역',
  '선호서비스'),
 ('RES00032',
  datetime.date(2023, 9, 12),
  datetime.date(2023, 9, 15),
  datetime.timedelta(seconds=39600),
  datetime.timedelta(seconds=61200),
  'SC00027',
  '인천광역시',
  '경기도',
  '서울특별시',
  '30~34',
  '45~49',
  '40~44',
  'M',
  '지정하지 않음',
  '재활운동보조',
  '빨래',
  '운전',
  '10000',
  '11000',
  '12000',
  '선호서비스',
  '선호나이대',
  '선호지역',
  '선호성별',
  '시급'),
 ('RES00033',
  datetime.date(2023, 9, 11),
  datetime.date(2023, 9, 12),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=57600),
  'SC00026',
  None,
  None,
  '경기도',
  None,
  None,
  '55~59',
  'W',
  '물리치료사',
  None,
  '재활운동보조',
  None,
  None,
  None,
  '13000',
  None,
  None,
  None,
  '선호서비스',
  '시급'),
 ('RES00034',
  None,
  None,
  None,
  None,
  'SC00006',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('RES00035',
  None,
  None,
  None,
  None,
  'SC00028',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('RES00036',
  datetime.date(2023, 9, 7),
  datetime.date(2023, 9, 11),
  datetime.timedelta(seconds=39600),
  datetime.timedelta(seconds=50400),
  'SC00028',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None),
 ('RES00037',
  datetime.date(2023, 9, 14),
  datetime.date(2023, 9, 22),
  datetime.timedelta(seconds=39600),
  datetime.timedelta(seconds=50400),
  'SC00028',
  None,
  None,
  '인천광역시',
  None,
  None,
  '40~44',
  'W',
  '지정하지 않음',
  None,
  None,
  '운전',
  None,
  None,
  '14000',
  None,
  None,
  None,
  '선호성별',
  '시급'),
 ('RES00038',
  datetime.date(2023, 9, 7),
  datetime.date(2023, 9, 11),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=64800),
  'SC00020',
  '서울특별시',
  '부산광역시',
  '경기도',
  '35~39',
  '30~34',
  '40~44',
  'W',
  '물리치료사',
  '재활운동보조',
  '요리',
  '목욕',
  '10000',
  '11000',
  '12000',
  '선호서비스',
  '선호나이대',
  '시급',
  '선호지역',
  '선호성별'),
 ('RES00039',
  datetime.date(2023, 9, 7),
  datetime.date(2023, 9, 11),
  datetime.timedelta(seconds=50400),
  datetime.timedelta(seconds=50400),
  'SC00003',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None))

In [22]:
res_df= pd.DataFrame(result)

In [23]:
res_df.columns = ['res_code', 'start_date', 'end_date', 'start_time', 'end_time', 'caretaker_code', 'pre_location_1', 'pre_location_2', 'pre_location_3', 'pre_age_1', 'pre_age_2', 'pre_age_3', 'pre_gender', 'pre_qual', 'pre_repre_1', 'pre_repre_2', 'pre_repre_3', 'pre_hourwage_1', 'pre_hourwage_2', 'pre_hourwage_3', 'rank1', 'rank2', 'rank3', 'rank4', 'rank5']

In [24]:
res_df.dropna(axis=0, how='any', inplace = True)

In [25]:
cursor = suitecare_data.cursor()
sql = "select * from caregiver;"
cursor.execute(sql)
care_result = cursor.fetchall()
care_result

(('asd1212',
  '1234',
  '문동주',
  'M',
  '1993-12-23',
  '01012121119',
  'asdb@naver.com',
  '(우)13547 경기 성남시 분당구 고기로 256-12 (동원동) ',
  'Y',
  'Y',
  'man.png',
  '목욕',
  '재활운동보조',
  '요리',
  '요양보호사',
  '서울특별시',
  '경기도',
  '인천광역시',
  '13000',
  '12000',
  '11000',
  datetime.date(2023, 8, 29),
  0),
 ('caregiver82214324',
  'asdf',
  '간병제공인',
  'M',
  '1980-05-26',
  '01010395313',
  'caregiver@suitecare.com',
  '(우) 08793 서울 관악구 낙성대역3길 3 (봉천동)',
  'Y',
  'Y',
  'caregiver82214324.jpg',
  '빨래',
  '요리',
  '재활운동보조',
  '요양보호사',
  '서울특별시',
  '부산광역시',
  '경기도',
  '14000',
  '11000',
  '15000',
  datetime.date(2023, 8, 22),
  0),
 ('caregiver830101047',
  'asdf',
  '간병제공인',
  'M',
  '1983-05-16',
  '01022949781',
  'caregiver@suitecare.com',
  '(우) 08793 서울 관악구 낙성대역3길 3 (봉천동)',
  'Y',
  'Y',
  'man.png',
  '빨래',
  '재활운동보조',
  '외출동행',
  '물리치료사',
  '경기도',
  '인천광역시',
  '서울특별시',
  '12000',
  '14000',
  '10000',
  datetime.date(2023, 8, 30),
  0),
 ('dong3',
  '1111',
  '이동진',
  'M',
  '1986-03-08',
  '01012341234',
  'aaaa@naver.com',
  '(우)08560 서울 금천구 독산로70길 84-5 (독산동, 롯데캐슬빌) ',
  'Y',
  'Y',
  'man.png',
  '요리',
  '목욕',
  '외출동행',
  '물리치료사',
  '서울특별시',
  '인천광역시',
  '경기도',
  '13000',
  '11000',
  '10000',
  datetime.date(2023, 8, 29),
  0),
 ('giver3',
  'giver',
  '김일',
  'M',
  '1977-07-09',
  '01012345588',
  'giver1@gmail.com',
  '(우)07411 서울 영등포구 가마산로 312 (대림동, 신동아아파트) 10111',
  'Y',
  'Y',
  'man.png',
  '재활운동보조',
  '외출동행',
  '요리',
  '간호사',
  '서울특별시',
  '경기도',
  '부산광역시',
  '12000',
  '11000',
  '10000',
  datetime.date(2023, 8, 29),
  0),
 ('hhkim',
  '1234',
  '김현희',
  'W',
  '1990-12-12',
  '010-1212-1212',
  '123456@naver.com',
  '(우)06376 서울 강남구 헌릉로 569 (세곡동) ',
  'N',
  'Y',
  'cat2.jpg',
  '재활운동보조',
  '목욕',
  '요리',
  '요양보호사',
  '서울특별시',
  '부산광역시',
  '경기도',
  '10000',
  '15000',
  '11000',
  datetime.date(2023, 8, 21),
  0),
 ('hhkim1',
  '1111',
  '김나리',
  'W',
  '1970-04-25',
  '010-1111-1111',
  '1@naver.com',
  '(우)48060 부산 해운대구 APEC로 17 (우동) 15',
  'N',
  'N',
  'man.png',
  '재활운동보조',
  '목욕',
  '요리',
  '요양보호사',
  '서울특별시',
  '경기도',
  '부산광역시',
  '11000',
  '15000',
  '10000',
  datetime.date(2023, 8, 21),
  0),
 ('hhkim123',
  '1234',
  '박강우',
  'M',
  '2009-07-01',
  '01097280192',
  '8@naver.com',
  '(우)08395 서울 구로구 디지털로24가길 2 (가리봉동) ',
  'Y',
  'Y',
  'man.png',
  '외출동행',
  '청소',
  '요리',
  '물리치료사',
  '경기도',
  '제주특별자치도',
  '부산광역시',
  '10000',
  '13000',
  '11000',
  datetime.date(2023, 8, 26),
  0),
 ('hhkim2',
  '2222',
  '김다나',
  'M',
  '1977-07-07',
  '010-7777-7777',
  '7@naver.com',
  '(우)13547 경기 성남시 분당구 고기로 25 (동원동) ',
  'Y',
  'Y',
  'man.png',
  '요리',
  '외출동행',
  '빨래',
  '물리치료사',
  '서울특별시',
  '경기도',
  '제주특별자치도',
  '15000',
  '11000',
  '13000',
  datetime.date(2023, 8, 21),
  0),
 ('hhkim3',
  '3333',
  '이라라',
  'W',
  '1980-08-08',
  '010-8888-8888',
  '8@naver.com',
  '(우)13586 경기 성남시 분당구 돌마로 478 (서현동) 22',
  'N',
  'N',
  'cat3.jpg',
  '운전',
  '외출동행',
  '요리',
  '간호사',
  '부산광역시',
  '부산광역시',
  '경기도',
  '10000',
  '13000',
  '11000',
  datetime.date(2023, 8, 21),
  0),
 ('hhkim4',
  '4444',
  '박미미',
  'W',
  '1988-12-12',
  '010-8888-1212',
  '12@naver.com',
  '(우)06035 서울 강남구 가로수길 5 (신사동) ',
  'N',
  'Y',
  'man.png',
  '요리',
  '외출동행',
  '빨래',
  '간호사',
  '서울특별시',
  '인천광역시',
  '경기도',
  '15000',
  '11000',
  '10000',
  datetime.date(2023, 8, 21),
  0),
 ('hhkim5',
  '5555',
  '최오형',
  'M',
  '1977-05-05',
  '010-5555-5555',
  '5@naver.com',
  '(우)13529 경기 성남시 분당구 분당내곡로 117 (백현동) ',
  'Y',
  'N',
  'man.png',
  '외출동행',
  '운전',
  '재활운동보조',
  '물리치료사',
  '서울특별시',
  '경기도',
  '인천광역시',
  '15000',
  '11000',
  '10000',
  datetime.date(2023, 8, 21),
  0),
 ('hhkim7',
  '7777',
  '김칠칠',
  'M',
  '1977-07-07',
  '01077777777',
  '7@naver.com',
  '(우)13547 경기 성남시 분당구 고기로 25 (동원동) 1',
  'Y',
  'Y',
  'man.png',
  '요리',
  '목욕',
  '재활운동보조',
  '간호사&요양보호사',
  '서울특별시',
  '부산광역시',
  '경기도',
  '12000',
  '11000',
  '13000',
  datetime.date(2023, 8, 25),
  0),
 ('hhkim8',
  '8888',
  '김팔팔',
  'M',
  '1980-08-08',
  '01088888888',
  '8@naver.com',
  '(우)05200 서울 강동구 가래여울길 8 (강일동) 11',
  'Y',
  'Y',
  'man.png',
  '재활운동보조',
  '외출동행',
  '운전',
  '물리치료사',
  '서울특별시',
  '경기도',
  '제주특별자치도',
  '11000',
  '12000',
  '10000',
  datetime.date(2023, 8, 29),
  0),
 ('jeje',
  '1111',
  '제제',
  'W',
  '2000-01-01',
  '01012341234',
  'aaaa@naver.com',
  '(우)12421 경기 디지털로 24 152(광명동) 192',
  'Y',
  'N',
  'jeje.png',
  '외출동행',
  '운전',
  '요리',
  '간호사',
  '서울특별시',
  '경기도',
  '인천광역시',
  '10000',
  '11000',
  '12000',
  datetime.date(2023, 8, 21),
  0),
 ('kimrujin',
  'love1103',
  '김쎔',
  'M',
  '2009-07-27',
  '01022567002',
  'kimrujin@naver.com',
  '(우)18472 경기 화성시 동탄대로22길 30 (영천동, 동탄센트럴자이) ',
  'Y',
  'Y',
  'man.png',
  '요리',
  '재활운동보조',
  '외출동행',
  '노인 수발&노인 목용',
  '서울특별시',
  '인천광역시',
  '경기도',
  '13000',
  '14000',
  '15000',
  datetime.date(2023, 9, 1),
  0),
 ('kin123',
  '123123',
  '박소담',
  'M',
  '1979-05-06',
  '010-8291-8881',
  'dos231q@naver.com',
  '(우)08844 서울 관악구 서원길 5 (신림동) ',
  'Y',
  'Y',
  'man.png',
  '목욕',
  '청소',
  '목욕',
  '간호사',
  '인천광역시',
  '부산광역시',
  '제주특별자치도',
  '10000',
  '11000',
  '12000',
  datetime.date(2023, 8, 23),
  0),
 ('sc001',
  'asdf',
  '스위트케어',
  'W',
  '1988-01-21',
  '01012341235',
  'asdf@asdf.com',
  '(우)05200 경기 광명시 철산3동 (철산동) 195',
  'Y',
  'N',
  'man.png',
  '외출동행',
  '재활운동보조',
  '청소',
  '물리치료사',
  '서울특별시',
  '인천광역시',
  '경기도',
  '13000',
  '11000',
  '10000',
  datetime.date(2023, 8, 21),
  0),
 ('test22',
  '1111',
  '사용자',
  'M',
  '2000-01-01',
  '01012341234',
  'bb@naver.com',
  '(우)13529 경기 성남시 분당구 판교역로 166 (백현동) ',
  'Y',
  'Y',
  'man.png',
  '청소',
  '요리',
  '외출동행',
  '물리치료사',
  '서울특별시',
  '경기도',
  '제주특별자치도',
  '11000',
  '15000',
  '13000',
  datetime.date(2023, 8, 22),
  0))

In [26]:
care_df = pd.DataFrame(care_result)

In [27]:
care_df.columns = ['g_id', 'g_pw', 'g_name', 'g_gender', 'g_birth', 'g_phone', 'g_email', 'g_address', 'g_sms_yn', 'g_email_yn', 'g_profile', 'g_service1', 'g_service2', 'g_service3', 'g_qualification', 'g_location1', 'g_location2', 'g_location3', 'g_hourwage1', 'g_hourwage2', 'g_hourwage3', 'g_signup_date', 'g_current_mileage']

In [28]:
care_df.drop(['g_current_mileage'], axis=1)

,g_id,g_pw,g_name,g_gender,g_birth,g_phone,g_email,g_address,g_sms_yn,g_email_yn,...,g_service2,g_service3,g_qualification,g_location1,g_location2,g_location3,g_hourwage1,g_hourwage2,g_hourwage3,g_signup_date
0,asd1212,1234,문동주,M,1993-12-23,01012121119,asdb@naver.com,(우)13547 경기 성남시 분당구 고기로 256-12 (동원동),Y,Y,...,재활운동보조,요리,요양보호사,서울특별시,경기도,인천광역시,13000,12000,11000,2023-08-29
1,caregiver82214324,asdf,간병제공인,M,1980-05-26,01010395313,caregiver@suitecare.com,(우) 08793 서울 관악구 낙성대역3길 3 (봉천동),Y,Y,...,요리,재활운동보조,요양보호사,서울특별시,부산광역시,경기도,14000,11000,15000,2023-08-22
2,caregiver830101047,asdf,간병제공인,M,1983-05-16,01022949781,caregiver@suitecare.com,(우) 08793 서울 관악구 낙성대역3길 3 (봉천동),Y,Y,...,재활운동보조,외출동행,물리치료사,경기도,인천광역시,서울특별시,12000,14000,10000,2023-08-30
3,dong3,1111,이동진,M,1986-03-08,01012341234,aaaa@naver.com,"(우)08560 서울 금천구 독산로70길 84-5 (독산동, 롯데캐슬빌)",Y,Y,...,목욕,외출동행,물리치료사,서울특별시,인천광역시,경기도,13000,11000,10000,2023-08-29
4,giver3,giver,김일,M,1977-07-09,01012345588,giver1@gmail.com,"(우)07411 서울 영등포구 가마산로 312 (대림동, 신동아아파트) 10111",Y,Y,...,외출동행,요리,간호사,서울특별시,경기도,부산광역시,12000,11000,10000,2023-08-29
5,hhkim,1234,김현희,W,1990-12-12,010-1212-1212,123456@naver.com,(우)06376 서울 강남구 헌릉로 569 (세곡동),N,Y,...,목욕,요리,요양보호사,서울특별시,부산광역시,경기도,10000,15000,11000,2023-08-21
6,hhkim1,1111,김나리,W,1970-04-25,010-1111-1111,1@naver.com,(우)48060 부산 해운대구 APEC로 17 (우동) 15,N,N,...,목욕,요리,요양보호사,서울특별시,경기도,부산광역시,11000,15000,10000,2023-08-21
7,hhkim123,1234,박강우,M,2009-07-01,01097280192,8@naver.com,(우)08395 서울 구로구 디지털로24가길 2 (가리봉동),Y,Y,...,청소,요리,물리치료사,경기도,제주특별자치도,부산광역시,10000,13000,11000,2023-08-26
8,hhkim2,2222,김다나,M,1977-07-07,010-7777-7777,7@naver.com,(우)13547 경기 성남시 분당구 고기로 25 (동원동),Y,Y,...,외출동행,빨래,물리치료사,서울특별시,경기도,제주특별자치도,15000,11000,13000,2023-08-21
9,hhkim3,3333,이라라,W,1980-08-08,010-8888-8888,8@naver.com,(우)13586 경기 성남시 분당구 돌마로 478 (서현동) 22,N,N,...,외출동행,요리,간호사,부산광역시,부산광역시,경기도,10000,13000,11000,2023-08-21
10,hhkim4,4444,박미미,W,1988-12-12,010-8888-1212,12@naver.com,(우)06035 서울 강남구 가로수길 5 (신사동),N,Y,...,외출동행,빨래,간호사,서울특별시,인천광역시,경기도,15000,11000,10000,2023-08-21
11,hhkim5,5555,최오형,M,1977-05-05,010-5555-5555,5@naver.com,(우)13529 경기 성남시 분당구 분당내곡로 117 (백현동),Y,N,...,운전,재활운동보조,물리치료사,서울특별시,경기도,인천광역시,15000,11000,10000,2023-08-21
12,hhkim7,7777,김칠칠,M,1977-07-07,01077777777,7@naver.com,(우)13547 경기 성남시 분당구 고기로 25 (동원동) 1,Y,Y,...,목욕,재활운동보조,간호사&요양보호사,서울특별시,부산광역시,경기도,12000,11000,13000,2023-08-25
13,hhkim8,8888,김팔팔,M,1980-08-08,01088888888,8@naver.com,(우)05200 서울 강동구 가래여울길 8 (강일동) 11,Y,Y,...,외출동행,운전,물리치료사,서울특별시,경기도,제주특별자치도,11000,12000,10000,2023-08-29
14,jeje,1111,제제,W,2000-01-01,01012341234,aaaa@naver.com,(우)12421 경기 디지털로 24 152(광명동) 192,Y,N,...,운전,요리,간호사,서울특별시,경기도,인천광역시,10000,11000,12000,2023-08-21
15,kimrujin,love1103,김쎔,M,2009-07-27,01022567002,kimrujin@naver.com,"(우)18472 경기 화성시 동탄대로22길 30 (영천동, 동탄센트럴자이)",Y,Y,...,재활운동보조,외출동행,노인 수발&노인 목용,서울특별시,인천광역시,경기도,13000,14000,15000,2023-09-01
16,kin123,123123,박소담,M,1979-05-06,010-8291-8881,dos231q@naver.com,(우)08844 서울 관악구 서원길 5 (신림동),Y,Y,...,청소,목욕,간호사,인천광역시,부산광역시,제주특별자치도,10000,11000,12000,2023-08-23
17,sc001,asdf,스위트케어,W,1988-01-21,01012341235,asdf@asdf.com,(우)05200 경기 광명시 철산3동 (철산동) 195,Y,N,...,재활운동보조,청소,물리치료사,서울특별시,인천광역시,경기도,13000,11000,10000,2023-08-21
18,test22,1111,사용자,M,2000-01-01,01012341234,bb@naver.com,(우)13529 경기 성남시 분당구 판교역로 166 (백현동),Y,Y,...,요리,외출동행,물리치료사,서울특별시,경기도,제주특별자치도,11000,15000,13000,2023-08-22

In [29]:
care_df.dropna(axis = 0, how='any', inplace = True)

In [13]:
# Function to calculate age based on birth date
def calculate_age(birth_date_str):
    birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d')
    today = datetime.today()
    age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
    return age

# Initialize dictionaries to store scores for each res_code
score_dict = defaultdict(lambda: defaultdict(int))
score_dict_repres = defaultdict(lambda : defaultdict(int))
score_dict_hourwages = defaultdict(lambda : defaultdict(int))
score_dict_gender = defaultdict(lambda: defaultdict(int))
score_dict_age = defaultdict(lambda: defaultdict(int))

# Loop through each row in res_df to get the pre_location, pre_gender, and pre_age preferences for each res_code
for index, row in res_df.iterrows():
    res_code = row['res_code']
    pre_locations = [row['pre_location_1'], row['pre_location_2'], row['pre_location_3']]
    pre_repres = [row['pre_repre_1'], row['pre_repre_2'], row['pre_repre_3']]
    pre_hourwages = [row['pre_hourwage_1'], row['pre_hourwage_2'], row['pre_hourwage_3']]
    pre_gender = row['pre_gender']
    pre_ages = [row['pre_age_1'], row['pre_age_2'], row['pre_age_3']]
    
    # Loop through each row in care_df to calculate the scores based on location, gender, and age preferences
    for idx, caregiver_row in care_df.iterrows():
        g_name = caregiver_row['g_name']
        
        g_locations = [caregiver_row['g_location1'], caregiver_row['g_location2'], caregiver_row['g_location3']]
        g_services = [caregiver_row['g_service1'], caregiver_row['g_service2'], caregiver_row['g_service3']]
        g_hourwages = [caregiver_row['g_hourwage1'], caregiver_row['g_hourwage2'], caregiver_row['g_hourwage3']]
        g_gender = caregiver_row['g_gender']
        g_birth = caregiver_row['g_birth']
        
        # Calculate age
        g_age = calculate_age(g_birth)
        
        # Calculate the scores based on location
        score = 0
        if pre_locations[0] == g_locations[0]:
            score += 10
        if pre_locations[0] == g_locations[1]:
            score += 8
        if pre_locations[0] == g_locations[2]:
            score += 6
        if pre_locations[1] == g_locations[0]:
            score += 7
        if pre_locations[1] == g_locations[1]:
            score += 5
        if pre_locations[1] == g_locations[2]:
            score += 3
        if pre_locations[2] == g_locations[0]:
            score += 4
        if pre_locations[2] == g_locations[1]:
            score += 2
        if pre_locations[2] == g_locations[2]:
            score += 1
        score_dict[res_code][g_name] = score

        
        # Calculate the scores based on service
        repres_score = 0
        if pre_repres[0] == g_services[0]:
            repres_score += 10
        if pre_repres[0] == g_services[1]:
            repres_score += 8
        if pre_repres[0] == g_services[2]:
            repres_score += 6
        if pre_repres[1] == g_services[0]:
            repres_score += 7
        if pre_repres[1] == g_services[1]:
            repres_score += 5
        if pre_repres[1] == g_services[2]:
            repres_score += 3
        if pre_repres[2] == g_services[0]:
            repres_score += 4
        if pre_repres[2] == g_services[1]:
            repres_score += 2
        if pre_repres[2] == g_services[2]:
            repres_score += 1
        score_dict_repres[res_code][g_name] = repres_score
        
        
        # Calculate the scores based on hourwage
        hourwages_score = 0
        if pre_hourwages[0] == g_hourwages[0]:
            hourwages_score += 10
        if pre_hourwages[0] == g_hourwages[1]:
            hourwages_score += 8
        if pre_hourwages[0] == g_hourwages[2]:
            hourwages_score += 6
        if pre_hourwages[1] == g_hourwages[0]:
            hourwages_score += 7
        if pre_hourwages[1] == g_hourwages[1]:
            hourwages_score += 5
        if pre_hourwages[1] == g_hourwages[2]:
            hourwages_score += 3
        if pre_hourwages[2] == g_hourwages[0]:
            hourwages_score += 4
        if pre_hourwages[2] == g_hourwages[1]:
            hourwages_score += 2
        if pre_hourwages[2] == g_hourwages[2]:
            hourwages_score += 1
        score_dict_hourwages[res_code][g_name] = hourwages_score
        
        
        
        # Calculate the scores based on gender
        gender_score = 0
        if pre_gender == 'M' and g_gender == 'M':
            gender_score += 5
        if pre_gender == 'W' and g_gender == 'W':
            gender_score += 5
        if pre_gender == 'M' and g_gender == '상관없음':
            gender_score += 3
        if pre_gender == '상관없음' and g_gender == 'M':
            gender_score += 3
        if pre_gender == '상관없음' and g_gender == 'W':
            gender_score += 3
        if pre_gender == 'W' and g_gender == '상관없음':
            gender_score += 3
        if pre_gender == 'M' and g_gender == 'W':
            gender_score += 1
        if pre_gender == 'W' and g_gender == 'M':
            gender_score += 1
        score_dict_gender[res_code][g_name] = gender_score

        # Calculate the scores based on age
        age_score = 0
        if pre_ages[0] in str(g_age):
            age_score += 5
        if pre_ages[1] in str(g_age):
            age_score += 3
        if pre_ages[2] in str(g_age):
            age_score += 1
        score_dict_age[res_code][g_name] = age_score

# Re-calculate the weighted scores based on rank preferences
final_weighted_score_dict = defaultdict(lambda: defaultdict(int))

# Loop through each row in res_df to get the preferences and ranks for each res_code
for index, row in res_df.iterrows():
    res_code = row['res_code']
    rank1 = row['rank1']
    rank2 = row['rank2']
    rank3 = row['rank3']
    rank4 = row['rank4']
    rank5 = row['rank5']
    
    # Determine the weights based on ranks
    weights = {'선호지역': 1, '선호성별': 1, '선호나이대': 1, '선호서비스':1, '시급':1}  # Initialize weights to 1
    if rank1 == '선호지역':
        weights['선호지역'] = 0.35
    if rank1 == '선호성별':
        weights['선호성별'] = 0.35
    if rank1 == '선호나이대':
        weights['선호나이대'] = 0.35
    if rank1 == '선호서비스':
        weights['선호서비스'] = 0.35
    if rank1 == '시급':
        weights['시급'] = 0.35
        
    if rank2 == '선호지역':
        weights['선호지역'] = 0.25
    if rank2 == '선호성별':
        weights['선호성별'] = 0.25
    if rank2 == '선호나이대':
        weights['선호나이대'] = 0.25
    if rank2 == '선호서비스':
        weights['선호서비스'] = 0.25
    if rank2 == '시급':
        weights['시급'] = 0.25
        
    if rank3 == '선호지역':
        weights['선호지역'] = 0.17
    if rank3 == '선호성별':
        weights['선호성별'] = 0.17
    if rank3 == '선호나이대':
        weights['선호나이대'] = 0.17
    if rank3 == '선호서비스':
        weights['선호서비스'] = 0.17
    if rank3 == '시급':
        weights['시급'] = 0.17
        
    if rank4 == '선호지역':
        weights['선호지역'] = 0.13
    if rank4 == '선호성별':
        weights['선호성별'] = 0.13
    if rank4 == '선호나이대':
        weights['선호나이대'] = 0.13
    if rank4 == '선호서비스':
        weights['선호서비스'] = 0.13
    if rank4 == '시급':
        weights['시급'] = 0.13
        
    if rank5 == '선호지역':
        weights['선호지역'] = 0.1
    if rank5 == '선호성별':
        weights['선호성별'] = 0.1
    if rank5 == '선호나이대':
        weights['선호나이대'] = 0.1
    if rank5 == '선호서비스':
        weights['선호서비스'] = 0.1
    if rank5 == '시급':
        weights['시급'] = 0.1
    
    
    # Calculate the final weighted score for each g_name based on the given ranks and weights
    for g_name in score_dict[res_code].keys():  
        location_score = score_dict[res_code][g_name] * weights['선호지역']
        repres_score = score_dict_repres[res_code][g_name] * weights['선호서비스']
        hourwages_score = score_dict_hourwages[res_code][g_name] * weights['시급']
        gender_score = score_dict_gender[res_code][g_name] * weights['선호성별']
        age_score = score_dict_age[res_code][g_name] * weights['선호나이대']
        
        # Calculate the final weighted score
        final_weighted_score = location_score + repres_score + hourwages_score + gender_score + age_score
        
        # Store the final weighted score for this res_code and g_name
        final_weighted_score_dict[res_code][g_name] = final_weighted_score

# Find the top 3 g_names for each res_code based on the final weighted scores
final_top_3_weighted_recommendations = {}
for res_code, scores in final_weighted_score_dict.items():
    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:3]
    final_top_3_weighted_recommendations[res_code] = [g_name for g_name, score in sorted_scores]

final_top_3_weighted_recommendations

{'RES00003': ['김팔팔', '김일', '스위트케어'],
 'RES00005': ['제제', '이동진', '박미미'],
 'RES00006': ['제제', '이라라', '김팔팔'],
 'RES00007': ['박강우', '박소담', '이라라'],
 'RES00008': ['간병제공인', '스위트케어', '문동주'],
 'RES00009': ['제제', '김일', '김팔팔'],
 'RES00010': ['김팔팔', '김일', '제제'],
 'RES00011': ['스위트케어', '제제', '김현희'],
 'RES00013': ['제제', '스위트케어', '김팔팔'],
 'RES00014': ['스위트케어', '최오형', '이동진'],
 'RES00016': ['김나리', '김칠칠', '이동진'],
 'RES00017': ['스위트케어', '박강우', '이동진'],
 'RES00018': ['김일', '김팔팔', '스위트케어'],
 'RES00019': ['김팔팔', '최오형', '제제'],
 'RES00020': ['최오형', '김다나', '김팔팔'],
 'RES00021': ['김나리', '문동주', '제제'],
 'RES00023': ['김일', '김팔팔', '스위트케어'],
 'RES00024': ['김일', '김팔팔', '스위트케어'],
 'RES00025': ['제제', '김팔팔', '박소담'],
 'RES00026': ['박소담', '문동주', '이동진'],
 'RES00027': ['박소담', '김팔팔', '제제'],
 'RES00028': ['김팔팔', '박소담', '제제'],
 'RES00029': ['간병제공인', '김일', '김팔팔'],
 'RES00030': ['김팔팔', '김나리', '박미미'],
 'RES00031': ['제제', '박강우', '김팔팔'],
 'RES00032': ['간병제공인', '김팔팔', '김일'],
 'RES00038': ['김현희', '김나리', '김일']}

In [30]:
# Function to calculate age based on birth date
def calculate_age(birth_date_str):
    birth_date = datetime.strptime(birth_date_str, '%Y-%m-%d')
    today = datetime.today()
    age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
    return age

# Initialize dictionaries to store scores for each res_code
score_dict = defaultdict(lambda: defaultdict(int))
score_dict_repres = defaultdict(lambda : defaultdict(int))
score_dict_hourwages = defaultdict(lambda : defaultdict(int))
score_dict_gender = defaultdict(lambda: defaultdict(int))
score_dict_age = defaultdict(lambda: defaultdict(int))

# Loop through each row in res_df to get the pre_location, pre_gender, and pre_age preferences for each res_code
for index, row in res_df.iterrows():
    res_code = row['res_code']
    pre_locations = [row['pre_location_1'], row['pre_location_2'], row['pre_location_3']]
    pre_repres = [row['pre_repre_1'], row['pre_repre_2'], row['pre_repre_3']]
    pre_hourwages = [row['pre_hourwage_1'], row['pre_hourwage_2'], row['pre_hourwage_3']]
    pre_gender = row['pre_gender']
    pre_ages = [row['pre_age_1'], row['pre_age_2'], row['pre_age_3']]
    
    # Loop through each row in care_df to calculate the scores based on location, gender, and age preferences
    for idx, caregiver_row in care_df.iterrows():
        g_id = caregiver_row['g_id']
        
        g_locations = [caregiver_row['g_location1'], caregiver_row['g_location2'], caregiver_row['g_location3']]
        g_services = [caregiver_row['g_service1'], caregiver_row['g_service2'], caregiver_row['g_service3']]
        g_hourwages = [caregiver_row['g_hourwage1'], caregiver_row['g_hourwage2'], caregiver_row['g_hourwage3']]
        g_gender = caregiver_row['g_gender']
        g_birth = caregiver_row['g_birth']
        
        # Calculate age
        g_age = calculate_age(g_birth)
        
        # Calculate the scores based on location
        score = 0
        if pre_locations[0] == g_locations[0]:
            score += 10
        if pre_locations[0] == g_locations[1]:
            score += 8
        if pre_locations[0] == g_locations[2]:
            score += 6
        if pre_locations[1] == g_locations[0]:
            score += 7
        if pre_locations[1] == g_locations[1]:
            score += 5
        if pre_locations[1] == g_locations[2]:
            score += 3
        if pre_locations[2] == g_locations[0]:
            score += 4
        if pre_locations[2] == g_locations[1]:
            score += 2
        if pre_locations[2] == g_locations[2]:
            score += 1
        score_dict[res_code][g_id] = score

        
        # Calculate the scores based on service
        repres_score = 0
        if pre_repres[0] == g_services[0]:
            repres_score += 10
        if pre_repres[0] == g_services[1]:
            repres_score += 8
        if pre_repres[0] == g_services[2]:
            repres_score += 6
        if pre_repres[1] == g_services[0]:
            repres_score += 7
        if pre_repres[1] == g_services[1]:
            repres_score += 5
        if pre_repres[1] == g_services[2]:
            repres_score += 3
        if pre_repres[2] == g_services[0]:
            repres_score += 4
        if pre_repres[2] == g_services[1]:
            repres_score += 2
        if pre_repres[2] == g_services[2]:
            repres_score += 1
        score_dict_repres[res_code][g_id] = repres_score
        
        
        # Calculate the scores based on hourwage
        hourwages_score = 0
        if pre_hourwages[0] == g_hourwages[0]:
            hourwages_score += 10
        if pre_hourwages[0] == g_hourwages[1]:
            hourwages_score += 8
        if pre_hourwages[0] == g_hourwages[2]:
            hourwages_score += 6
        if pre_hourwages[1] == g_hourwages[0]:
            hourwages_score += 7
        if pre_hourwages[1] == g_hourwages[1]:
            hourwages_score += 5
        if pre_hourwages[1] == g_hourwages[2]:
            hourwages_score += 3
        if pre_hourwages[2] == g_hourwages[0]:
            hourwages_score += 4
        if pre_hourwages[2] == g_hourwages[1]:
            hourwages_score += 2
        if pre_hourwages[2] == g_hourwages[2]:
            hourwages_score += 1
        score_dict_hourwages[res_code][g_id] = hourwages_score
        
        
        
        # Calculate the scores based on gender
        gender_score = 0
        if pre_gender == 'M' and g_gender == 'M':
            gender_score += 5
        if pre_gender == 'W' and g_gender == 'W':
            gender_score += 5
        if pre_gender == 'M' and g_gender == '상관없음':
            gender_score += 3
        if pre_gender == '상관없음' and g_gender == 'M':
            gender_score += 3
        if pre_gender == '상관없음' and g_gender == 'W':
            gender_score += 3
        if pre_gender == 'W' and g_gender == '상관없음':
            gender_score += 3
        if pre_gender == 'M' and g_gender == 'W':
            gender_score += 1
        if pre_gender == 'W' and g_gender == 'M':
            gender_score += 1
        score_dict_gender[res_code][g_id] = gender_score

        # Calculate the scores based on age
        age_score = 0
        if pre_ages[0] in str(g_age):
            age_score += 5
        if pre_ages[1] in str(g_age):
            age_score += 3
        if pre_ages[2] in str(g_age):
            age_score += 1
        score_dict_age[res_code][g_id] = age_score

# Re-calculate the weighted scores based on rank preferences
final_weighted_score_dict = defaultdict(lambda: defaultdict(int))

# Loop through each row in res_df to get the preferences and ranks for each res_code
for index, row in res_df.iterrows():
    res_code = row['res_code']
    rank1 = row['rank1']
    rank2 = row['rank2']
    rank3 = row['rank3']
    rank4 = row['rank4']
    rank5 = row['rank5']
    
    # Determine the weights based on ranks
    weights = {'선호지역': 1, '선호성별': 1, '선호나이대': 1, '선호서비스':1, '시급':1}  # Initialize weights to 1
    if rank1 == '선호지역':
        weights['선호지역'] = 0.35
    if rank1 == '선호성별':
        weights['선호성별'] = 0.35
    if rank1 == '선호나이대':
        weights['선호나이대'] = 0.35
    if rank1 == '선호서비스':
        weights['선호서비스'] = 0.35
    if rank1 == '시급':
        weights['시급'] = 0.35
        
    if rank2 == '선호지역':
        weights['선호지역'] = 0.25
    if rank2 == '선호성별':
        weights['선호성별'] = 0.25
    if rank2 == '선호나이대':
        weights['선호나이대'] = 0.25
    if rank2 == '선호서비스':
        weights['선호서비스'] = 0.25
    if rank2 == '시급':
        weights['시급'] = 0.25
        
    if rank3 == '선호지역':
        weights['선호지역'] = 0.17
    if rank3 == '선호성별':
        weights['선호성별'] = 0.17
    if rank3 == '선호나이대':
        weights['선호나이대'] = 0.17
    if rank3 == '선호서비스':
        weights['선호서비스'] = 0.17
    if rank3 == '시급':
        weights['시급'] = 0.17
        
    if rank4 == '선호지역':
        weights['선호지역'] = 0.13
    if rank4 == '선호성별':
        weights['선호성별'] = 0.13
    if rank4 == '선호나이대':
        weights['선호나이대'] = 0.13
    if rank4 == '선호서비스':
        weights['선호서비스'] = 0.13
    if rank4 == '시급':
        weights['시급'] = 0.13
        
    if rank5 == '선호지역':
        weights['선호지역'] = 0.1
    if rank5 == '선호성별':
        weights['선호성별'] = 0.1
    if rank5 == '선호나이대':
        weights['선호나이대'] = 0.1
    if rank5 == '선호서비스':
        weights['선호서비스'] = 0.1
    if rank5 == '시급':
        weights['시급'] = 0.1
    
    
    # Calculate the final weighted score for each g_name based on the given ranks and weights
    for g_id in score_dict[res_code].keys():  
        location_score = score_dict[res_code][g_id] * weights['선호지역']
        repres_score = score_dict_repres[res_code][g_id] * weights['선호서비스']
        hourwages_score = score_dict_hourwages[res_code][g_id] * weights['시급']
        gender_score = score_dict_gender[res_code][g_id] * weights['선호성별']
        age_score = score_dict_age[res_code][g_id] * weights['선호나이대']
        
        # Calculate the final weighted score
        final_weighted_score = location_score + repres_score + hourwages_score + gender_score + age_score
        
        # Store the final weighted score for this res_code and g_name
        final_weighted_score_dict[res_code][g_id] = final_weighted_score

# Find the top 3 g_names for each res_code based on the final weighted scores
final_top_3_weighted_recommendations = {}
for res_code, scores in final_weighted_score_dict.items():
    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:3]
    final_top_3_weighted_recommendations[res_code] = [g_id for g_id, score in sorted_scores]

final_top_3_weighted_recommendations

{'RES00003': ['hhkim8', 'giver3', 'sc001'],
 'RES00005': ['jeje', 'dong3', 'hhkim4'],
 'RES00006': ['jeje', 'hhkim3', 'hhkim8'],
 'RES00007': ['hhkim123', 'kin123', 'hhkim3'],
 'RES00008': ['caregiver830101047', 'sc001', 'asd1212'],
 'RES00009': ['jeje', 'giver3', 'hhkim8'],
 'RES00010': ['hhkim8', 'giver3', 'jeje'],
 'RES00011': ['sc001', 'jeje', 'hhkim'],
 'RES00013': ['jeje', 'sc001', 'hhkim8'],
 'RES00014': ['sc001', 'hhkim5', 'dong3'],
 'RES00016': ['hhkim1', 'hhkim7', 'dong3'],
 'RES00017': ['sc001', 'hhkim123', 'dong3'],
 'RES00018': ['giver3', 'hhkim8', 'sc001'],
 'RES00019': ['hhkim8', 'hhkim5', 'jeje'],
 'RES00020': ['hhkim5', 'hhkim2', 'hhkim8'],
 'RES00021': ['hhkim1', 'asd1212', 'jeje'],
 'RES00023': ['giver3', 'hhkim8', 'sc001'],
 'RES00024': ['giver3', 'hhkim8', 'sc001'],
 'RES00025': ['jeje', 'hhkim8', 'kin123'],
 'RES00026': ['kin123', 'asd1212', 'dong3'],
 'RES00027': ['kin123', 'hhkim8', 'jeje'],
 'RES00028': ['hhkim8', 'kin123', 'jeje'],
 'RES00029': ['caregiver830101047', 'giver3', 'hhkim8'],
 'RES00030': ['hhkim8', 'hhkim1', 'hhkim4'],
 'RES00031': ['jeje', 'hhkim123', 'hhkim8'],
 'RES00032': ['caregiver830101047', 'hhkim8', 'giver3'],
 'RES00038': ['hhkim', 'hhkim1', 'giver3']}

In [31]:
print(list((final_top_3_weighted_recommendations.keys, final_top_3_weighted_recommendations.values)))

[<built-in method keys of dict object at 0x0000020AC5BB2228>, <built-in method values of dict object at 0x0000020AC5BB2228>]

In [32]:
recomm_df =list(final_top_3_weighted_recommendations.items())

In [33]:
recomm_df = pd.DataFrame(recomm_df)
recomm_df

           0                                     1
0   RES00003               [hhkim8, giver3, sc001]
1   RES00005                 [jeje, dong3, hhkim4]
2   RES00006                [jeje, hhkim3, hhkim8]
3   RES00007            [hhkim123, kin123, hhkim3]
4   RES00008  [caregiver830101047, sc001, asd1212]
5   RES00009                [jeje, giver3, hhkim8]
6   RES00010                [hhkim8, giver3, jeje]
7   RES00011                  [sc001, jeje, hhkim]
8   RES00013                 [jeje, sc001, hhkim8]
9   RES00014                [sc001, hhkim5, dong3]
10  RES00016               [hhkim1, hhkim7, dong3]
11  RES00017              [sc001, hhkim123, dong3]
12  RES00018               [giver3, hhkim8, sc001]
13  RES00019                [hhkim8, hhkim5, jeje]
14  RES00020              [hhkim5, hhkim2, hhkim8]
15  RES00021               [hhkim1, asd1212, jeje]
16  RES00023               [giver3, hhkim8, sc001]
17  RES00024               [giver3, hhkim8, sc001]
18  RES00025                [jeje, hhkim8, kin123]
19  RES00026              [kin123, asd1212, dong3]
20  RES00027                [kin123, hhkim8, jeje]
21  RES00028                [hhkim8, kin123, jeje]
22  RES00029  [caregiver830101047, giver3, hhkim8]
23  RES00030              [hhkim8, hhkim1, hhkim4]
24  RES00031              [jeje, hhkim123, hhkim8]
25  RES00032  [caregiver830101047, hhkim8, giver3]
26  RES00038               [hhkim, hhkim1, giver3]

In [34]:
recomm_df.to_csv("recomm_df.csv", index = False, encoding = 'cp949')

recomm_df =pd.read_csv("recomm_df.csv", names=['피간병인','간병인'])